include(FetchContent)

FetchContent_Declare(
    Catch2
    GIT_REPOSITORY https://github.com/catchorg/Catch2.git
    GIT_TAG        v3.5.2)
FetchContent_MakeAvailable(Catch2)

add_executable(VCOTunerTests
    CvScalingTests.cpp
    ClockCalibratorTests.cpp
    PeriodDetectorTests.cpp
    MeasurementStatisticsTests.cpp
    MeasurementErrorTests.cpp
    MeasurementTimingTests.cpp)

target_link_libraries(VCOTunerTests PRIVATE vcotuner_dsp Catch2::Catch2WithMain)

list(APPEND CMAKE_MODULE_PATH ${catch2_SOURCE_DIR}/extras)
include(Catch)
catch_discover_tests(VCOTunerTests DISCOVERY_MODE PRE_TEST)
